/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        espresso: '#2C2926',
        charcoal: '#2C2926',
        'espresso-light': '#3D3632',
        sand: '#D8C9B5',
        'warm-sand': '#D8C9B5',
        'border-sand': '#D8C9B5',
        ivory: '#F7F4EE',
        'warm-ivory': '#F7F4EE',
        'warm-offwhite': '#F7F4EE',
        'warm-alabaster': '#F7F4EE',
        'ivory-dark': '#EDE8DF',
        olive: '#48563A',
        'muted-olive': '#48563A',
        taupe: '#A69B8C',
        'soft-taupe': '#A69B8C',
        'mid-gray': '#A69B8C',
        terracotta: '#48563A',
        'antique-gold': '#48563A',
        'gold-accent': '#D8C9B5',
      },
      fontFamily: {
        serif: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
        display: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
        sans: ['Inter', 'Manrope', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        body: ['Inter', 'Manrope', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
      },
      borderRadius: {
        btn: '6px',
        card: '8px',
        sm: '4px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        '3xl': '20px',
      },
      boxShadow: {
        card: '0 2px 8px rgba(27, 31, 36, 0.05)',
        warm: '0 2px 8px rgba(27, 31, 36, 0.08)',
        subtle: '0 1px 4px rgba(27, 31, 36, 0.04)',
        hover: '0 6px 16px rgba(27, 31, 36, 0.08)',
        elevated: '0 12px 28px rgba(27, 31, 36, 0.10)',
      },
    },
  },
  plugins: [],
}
